### ISSUE TITLE
Refactor for use as a library

### ISSUE THREAD

**Issue by mholt** [skanehira/tson#3]
I know this sounds a bit crazy, but it would be great if this could be used as a library. Basically, separate out the parts of this tool that deal with the command line, and put the code that actually does the TUI stuff and tree nav in its own package.

For example (without having given it too much though), this would be very nice:

```go
myJSON := []byte{...}
updatedJSON, err := tson.Edit(myJSON)
// a TUI screen would cover the terminal at this point,
// and relinquish itself when done editing, while
// returning the resulting JSON bytes
```

I could see myself embedding something like this into [Caddy 2](https://github.com/caddyserver/caddy/tree/v2), which is configured entirely by JSON. But only if it can be used as a library like this.

Imagine starting up your web server in some interactive/dashboard mode, and being able to watch it in real-time in your terminal (kind of like what htop does, but just for your server), while being able to edit its configuration right there as well! Super useful for development too!

Anyway, I'm excited about this project, I hope you'll keep developing it.

**Comment by skanehira** [comment]
@mholt Good idea!!
I'll implement it.

**Comment by skanehira** [comment]
@mholt I implemented this feature. you can use tson as a library :)
https://github.com/skanehira/tson#use-tson-as-a-library-in-your-application

**Comment by mholt** [comment]
Very cool! That's super easy to use, thanks.

Looking forward to building a CLI dashboard for Caddy one of these days :)
